### ISSUE TITLE
Build fails when using bash shell

### ISSUE THREAD

**Issue by WalterSmuts** [compnerd/gha-setup-swift#18]
I have created a [minimal reproduction repo](https://github.com/WalterSmuts/swift-windows). I have an example of a simple hello world program [passing the build step](https://github.com/WalterSmuts/swift-windows-ci/actions/runs/6071315278) and [a failure](https://github.com/WalterSmuts/swift-windows-ci/actions/runs/6071319039) after adding the following patch:
```diff
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -1,5 +1,9 @@
 name: Build and test

+defaults:
+  run:
+    shell: bash {0}
+
 on: [push]

 jobs:
```

The resulting error is:
```
error: 'swift-windows-ci': Invalid manifest (compiled with: ["C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\bin\\swiftc.exe", "-L", "C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift\\pm\\ManifestAPI", "-lPackageDescription", "-sdk", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\SDKs\\Windows.sdk", "-libc", "MD", "-I", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows", "-I", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\x86_64", "-L", "C:\\Library\\Developer\\Platforms\\Windows.platform\\Developer\\Library\\XCTest-development\\usr\\lib\\swift\\windows\\x86_64", "-use-ld=lld", "-swift-version", "5", "-I", "C:\\Library\\Developer\\Toolchains\\unknown-Asserts-development.xctoolchain\\usr\\lib\\swift\\pm\\ManifestAPI", "-package-description-version", "5.8.0", "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\TemporaryDirectory.fU1bx7\\manifest.swift", "-Xfrontend", "-disable-implicit-concurrency-module-import", "-Xfrontend", "-disable-implicit-string-processing-module-import", "-v", "-o", "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\TemporaryDirectory.LTYdrU\\swift-windows-ci-manifest.exe"])
```
When searching for `"Invalid manifest" windows swift` you get [some references to issues relating to usage of different shells](https://stackoverflow.com/questions/71991468/swift-error-on-windows-invalidmanifestformat-missing-or-empty-json-output-from).

**Comment by WalterSmuts** [comment]
Also see https://github.com/apple/swift-package-manager/issues/5886

**Comment by WalterSmuts** [comment]
Perhaps these environment variables are not being exported to different shells? I'm not very experienced with windows things so may be wayyy off:
```pwsh
    - name: Install Swift ${{ inputs.tag }}
      if: runner.os == 'Windows'
      run: |
        function Update-EnvironmentVariables {
          foreach ($level in "Machine", "User") {
            [Environment]::GetEnvironmentVariables($level).GetEnumerator() | % {
              # For Path variables, append the new values, if they're not already in there
              if ($_.Name -Match 'Path$') {
                $_.Value = ($((Get-Content "Env:$($_.Name)") + ";$($_.Value)") -Split ';' | Select -Unique) -Join ';'
              }
              $_
            } | Set-Content -Path { "Env:$($_.Name)" }
          }
        }
```

**Comment by compnerd** [comment]
Bash is not a supported shell for Swift (on Windows).  Please use cmd or powershell.  The toolchain itself will not function, this is not an issue with the action.

Changing the shell on the action won’t help prevent issues, the usage of swift itself must remain on cmd or powershell.  bash runs under mingw and is a different environment.  I’m not sure that this is actionable here, so I’m closing it.  If there’s something that I didn’t consider as a solution please reopen with the additional context.

**Comment by compnerd** [comment]
> Where is this documented?

It isn't very well documented, improvements for the documentation on Windows are welcome at https://github.com/apple/swift-org-website

> Any ideas how the environment actually differs? Environment variables? More?

More, fundamentally it runs in MinGW rather than the Win32 environment, which impacts a number of things including environment and file system paths.
