### ISSUE TITLE
create a release tag

### ISSUE THREAD

**Issue by kelvin13** [compnerd/gha-setup-swift#7]
can we get a release tag, like v0.1.0?

**Comment by compnerd** [comment]
Hmm, let me bump test with 5.7 and main, and if both of those continue to work with main, I'm happy to tag a v0.1.0.

**Comment by compnerd** [comment]
I knew that I was expecting something to be broken ... https://github.com/compnerd/swift-win32/runs/7546429823?check_suite_focus=true

This shouldn't be too terrible to fix.  There was some shuffling recently where vcruntime.{modulemap,apinotes} was renamed.  We should support both the new name and the old name.

**Comment by compnerd** [comment]
Tagged v0.0.1.
