### ISSUE TITLE
malformed host triple error

### ISSUE THREAD

**Issue by kelvin13** [compnerd/gha-setup-swift#9]
occasionally, my CI workflows fail with:

```
 compnerd.org Swift version 5.5.3 (swift-5.5.3-RELEASE)
Target: x86_64-unknown-windows-msvc
TSCUtility/Triple.swift:154: Fatal error: could not determine host triple: malformed
error: unable to invoke subcommand: C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin\swift-build.exe ()
Error: Process completed with exit code 1.
```

[full log](https://github.com/kelvin13/swift-json/runs/7549928937?check_suite_focus=true)

re-running the jobs usually [succeeds](https://github.com/kelvin13/swift-json/runs/7551249566?check_suite_focus=true).

**Comment by compnerd** [comment]
I am almost certain that this is a bug in SPM (or at least how SPM uses Foundation).  Again, there is nothing that the action can do here - these are bugs in Swift Package Manager.  SPM creates a subprocess which does not execute properly resulting in no output, which then is treated as a failure.
